# BUILD .VENV
FROM python:3.13.9-alpine3.22 AS builder
WORKDIR /venv_build
COPY pyproject.toml uv.lock ./
RUN apk add uv && uv sync

# RUNTIME
FROM python:3.13.9-alpine3.22 AS runtime

WORKDIR /sharecare
COPY --from=builder /venv_build/.venv /sharecare/.venv
COPY ./app ./app
ENV PATH="/sharecare/.venv/bin:$PATH"



