services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    environment:
      - PORT=8000
    volumes:
      - ./app:/sharecare/app
    restart: unless-stopped